# Generated by Django 4.0.1 on 2024-01-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userprofile_age_alter_userprofile_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='food_allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_habit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='junk_food',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meal_day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(default='956aab4b-3015-4fd9-8a7c-359bb8e63311', max_length=40, unique=True),
        ),
    ]
