# Generated by Django 4.0.1 on 2024-01-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_active_day_userprofile_breakfast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='myapp/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(default='768fc953-dfb5-4f96-88d0-3df9ed74a82a', max_length=40, unique=True),
        ),
    ]
